name: spotify_ui_challenge
description: Spotify UI Challenge

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/

  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/GothamBold.ttf
        - asset: fonts/GothamLight.ttf
        - asset: fonts/GothamMedium.ttf